### ISSUE TITLE
MetaImage.cpp ne compile pas

### ISSUE THREAD

**Issue by eliuranel** [rcharron/climgRL#1]
(chez moi en tout cas)

**Comment by rcharron** [comment]
Je sais. Je vais corriger cela. 

---

Raphaël Charrondière

ENS de Lyon 

Le 2015-04-26 11:29, eliuranel a écrit : 

> (chez moi en tout cas) 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1] https://github.com/rcharron/climgRL/issues/1

**Comment by rcharron** [comment]
Fixé
